name: "run tests"
on:
  pull_request:
    branches:
      - main

jobs:
    test:
        permissions:
          contents: read
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
             node-version: '22'
          - run: wget https://raw.githubusercontent.com/openkfw/open-geodata-model/main/references/project_core_schema_en.json && ls -lah
          - name: Install Dependencies
            run: cd frontend && npm ci
          - name: test
            run: cd frontend && npm test -- --watchAll=false
          - uses: ArtiomTr/jest-coverage-report-action@v2

